### ISSUE TITLE
Server error when creating an order

### ISSUE THREAD

**Issue by OlivierDevMaster** [code-verse-unity/car-sales-management#18]
There is a Server Error when attempting to create an order. 

# How to recreate the problem
- Get this last commit 3a0a80ec4422916498aad7d857ea298e6dacab9e
- Go to /orders/create
- Try to create one
- Unexpected behaviour: Redirection to the server error page

# Notes
- The clientId is defined on the $body request
- The carsIds also is defined, may be a string or an array
- Same for the quantities. Defined, string or array

**Comment by Ismael-Rakotondrazaka** [comment]
Make Sure you have run
```sh
php migrate.php
```

**Comment by OlivierDevMaster** [comment]
Dropping of the tables and updating the fake dummy data to have **21 characters** id fix the problem
